# Generated by Django 4.2 on 2023-12-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='optionText',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='id_Question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='QA.question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResponsesQuestion',
        ),
    ]
